### PR TITLE
Event creation system

### PR DESCRIPTION
**Pull request by Emulai**

### CODE REVIEW

**Comment by Emulai** [comment]
Base event creation system ready to be merged with `review` for testing - still pending final decisions on event/stat structure & interactions

**Comment by FreshlySketched** [comment]
Code is commented nicely, I will test on my system asap

**Review by FreshlySketched — COMMENTED** [review]
continuing review

**Review by FreshlySketched — APPROVED** [review]
Tested and all works nicely. Great job, David
Note: I tested on 2020.3.12f which is only a couple small patches higher than the 2020.3.10f at uni.

**Pull request merged**
